#!/bin/zsh
# Thanks https://github.com/hpcsc/dotfiles/blob/63f194aa553ef83f9edec76991f2265f7962b00e/link/common/zsh/.functions/fzf-functions/fcm

SELECTED_AUTHORS=$(git shortlog -sne | awk '{$1=""}1' | fzf -m)

MESSAGE="\n\n"
# convert newline-delimited string to array, zsh way: https://stackoverflow.com/a/2930519
AUTHORS=("${(f)SELECTED_AUTHORS}")
for AUTHOR in $AUTHORS[@]; do
  MESSAGE="${MESSAGE}Co-authored-by: ${AUTHOR}\n"
done

if [[ "$1" == "-m" ]]; then
  git commit -m "$2$(echo -e ${MESSAGE})"
else 
  git commit $@ -t <(echo -e ${MESSAGE})
fi

