#!/bin/bash

DOTFILES_ROOT="`pwd`"

git pull

function install_dotfiles() {
    for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`; do
      dest="$HOME/.`basename \"${source%.*}\"`"

      if [ -f $dest ] || [ -d $dest ] ; then
        rm -rf $dest
      fi

      ln -s $source $dest
    done

    # Fix .zshrc
    rm ~/.zshrc
    ln -s "$HOME/.dotfiles/zsh/zshrc.symlink" $HOME/.zshrc

    # Load zshrc
    zsh ~/.zshrc
}

if [ "$1" = "--force" -o "$1" = "-f" ] ; then
    install_dotfiles
else
    echo "This may overwrite existing files in your home directory. Are you sure? (y/n)"
    read -r -n1 REPLY
    echo

    if [[ $REPLY =~ ^[Yy]$ ]] ; then
        install_dotfiles
    fi
fi

unset install_dotfiles
