#!/bin/bash

DOTFILES_ROOT="`pwd`"

git pull

function doIt() {
    for source in `find $DOTFILES_ROOT -maxdepth 2 -name \*.symlink`; do
      dest="$HOME/.`basename \"${source%.*}\"`"

      if [ -f $dest ] || [ -d $dest ];then
        rm -rf $dest
      fi

      ln -s $source $dest
    done


    if [ "$(uname -s)" == "Darwin" ]; then
      cd
      brew bundle
    fi
}

if [ "$1" = "--force" -o "$1" = "-f" ]; then
    doIt
else
    echo "This may overwrite existing files in your home directory. Are you sure? (y/n)"
    read -k
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        doIt
    fi
fi
unset doIt
source ~/.zshrc
