# For more information to the git aliases, look into .gitconfig
alias g="git"

alias gauthors="git authors"
alias gb="git b"
alias gc="git c"
alias gca="git ca"
alias gcaa="git caa"
alias gcaae="git caae"
alias gcl="git cl"
alias gco="git co"
alias gcob="git cob"
alias gd="git d"
alias gl="git l"
alias gps="git ps"
alias gpsu="git psu"
alias gr="git r"
alias gri="git ri"
alias gri="git ri"
alias grc="git rc"
alias gra="git ra"
alias grs="git rs"
alias gs="git s"
alias gst="git st"
alias gstl="git stl"
alias gstp="git stp"
alias gu="git up"
