# For more information to the git aliases, look into .gitconfig
alias gca="git ca"
alias gcaa="git caa"
alias gco="git co"
alias gl="git l"
alias gps="git push"
alias gpsu="git psu"
alias gs="git s"
alias gst="git st"
alias gstp="git stp"
alias gu="git up"
